### PR TITLE
Fix selection not showing on iOS 15

### PR DESCRIPTION
**Pull request by galbernator**
Changes naming from overriding `isSelected` on the `CalendarDayCell` to `isPicked` and assigns the selected date on load when the cells are not yet retrievable from the `collectionView`.

This is an attempt at following the pattern that was established in https://github.com/outdoorsy/outdoorsy-ios-app/pull/1282

### CODE REVIEW

**Review by DrBeak1 — COMMENTED** [review]
Code looks good. Is there a way to compile and test this?

**Comment by galbernator** [comment]
It looks like they do not have tests for this repo. The test files are there, but are just the boilerplate test code that just passes. Not sure that getting this set up with CI (assuming that is what is meant by "compile and test" in the comment above) is worth the effort if we would need to write tests for it.

**Review by johnoutdoorsy — APPROVED** [review]

**Comment by johnoutdoorsy** [comment]
I think he means, how do we test this to see if the new code works on simulator. But I believe that's what this PR is: https://github.com/outdoorsy/outdoorsy-ios-app/pull/1294

**Comment by DrBeak1** [comment]
@galbernator - Yes, What @johnoutdoorsy said ^ -- But he provided the answer there too. So everything is good 👍🏻

**Review by DrBeak1 — APPROVED** [review]

**Pull request merged**
